//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Euye12
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Город.
    /// </summary>
    // *** Start programmer edit section *** (Город CustomAttributes)

    // *** End programmer edit section *** (Город CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГородE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("ГородL", new string[] {
            "Наименование as \'Наименование\'"})]
    public class Город : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private IIS.Euye12.Улица fУлица;
        
        // *** Start programmer edit section *** (Город CustomMembers)

        // *** End programmer edit section *** (Город CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Город.Наименование CustomAttributes)

        // *** End programmer edit section *** (Город.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Город.Наименование Get start)

                // *** End programmer edit section *** (Город.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Город.Наименование Get end)

                // *** End programmer edit section *** (Город.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Город.Наименование Set start)

                // *** End programmer edit section *** (Город.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Город.Наименование Set end)

                // *** End programmer edit section *** (Город.Наименование Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Euye12.Улица.
        /// </summary>
        // *** Start programmer edit section *** (Город.Улица CustomAttributes)

        // *** End programmer edit section *** (Город.Улица CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Улица"})]
        public virtual IIS.Euye12.Улица Улица
        {
            get
            {
                // *** Start programmer edit section *** (Город.Улица Get start)

                // *** End programmer edit section *** (Город.Улица Get start)
                IIS.Euye12.Улица result = this.fУлица;
                // *** Start programmer edit section *** (Город.Улица Get end)

                // *** End programmer edit section *** (Город.Улица Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Город.Улица Set start)

                // *** End programmer edit section *** (Город.Улица Set start)
                this.fУлица = value;
                // *** Start programmer edit section *** (Город.Улица Set end)

                // *** End programmer edit section *** (Город.Улица Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГородE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГородE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГородE", typeof(IIS.Euye12.Город));
                }
            }
            
            /// <summary>
            /// "ГородL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГородL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГородL", typeof(IIS.Euye12.Город));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Город.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfГород CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfГород CustomAttributes)
    public class DetailArrayOfГород : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Euye12.DetailArrayOfГород members)

        // *** End programmer edit section *** (IIS.Euye12.DetailArrayOfГород members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Город by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Город.
        /// </summary>
        public DetailArrayOfГород(IIS.Euye12.Улица fУлица) : 
                base(typeof(Город), ((ICSSoft.STORMNET.DataObject)(fУлица)))
        {
        }
        
        public IIS.Euye12.Город this[int index]
        {
            get
            {
                return ((IIS.Euye12.Город)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Euye12.Город dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
